[package]
edition.workspace = true
license.workspace = true
name = "xedoc-features"
version.workspace = true

[lib]
doctest = false
name = "xedoc_features"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
xedoc-otel = { workspace = true }
xedoc-protocol = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
