[package]
edition.workspace = true
license.workspace = true
name = "xedoc-plugin"
version.workspace = true

[lib]
doctest = false
name = "xedoc_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
xedoc-config = { workspace = true }
xedoc-protocol = { workspace = true }
xedoc-utils-absolute-path = { workspace = true }
xedoc-utils-path-uri = { workspace = true }
xedoc-utils-plugins = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
