[package]
edition.workspace = true
license.workspace = true
name = "codex-core-utils"
version.workspace = true

[lib]
name = "codex_core_utils"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
rand = { workspace = true }
tracing = { workspace = true, features = ["log"] }
