[package]
edition.workspace = true
license.workspace = true
name = "xedoc-tool-output-reduce"
version.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
xedoc-protocol = { workspace = true }
xedoc-utils-absolute-path = { workspace = true }
xedoc-utils-string = { workspace = true }
xedoc-utils-output-truncation = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
