mod app_mcp_routing;
mod discoverable;
pub mod loader;
mod manager;
mod provider;
pub mod remote;
pub mod remote_bundle;
pub mod remote_legacy;
pub mod startup_sync;
#[cfg(test)]
mod test_support;
pub mod toggles;
mod tool_suggest_metadata;

pub use codex_core_plugin_marketplace::OPENAI_API_CURATED_MARKETPLACE_NAME;
pub use codex_core_plugin_marketplace::OPENAI_BUNDLED_MARKETPLACE_NAME;
pub use codex_core_plugin_marketplace::OPENAI_CURATED_MARKETPLACE_NAME;
pub(crate) use codex_core_plugin_marketplace::command_migration;
pub use codex_core_plugin_marketplace::installed_marketplaces;
pub use codex_core_plugin_marketplace::is_openai_curated_marketplace_name;
pub use codex_core_plugin_marketplace::manifest;
pub use codex_core_plugin_marketplace::marketplace;
pub use codex_core_plugin_marketplace::marketplace_add;
pub(crate) use codex_core_plugin_marketplace::marketplace_policy;
pub use codex_core_plugin_marketplace::marketplace_remove;
pub use codex_core_plugin_marketplace::marketplace_upgrade;
pub(crate) use codex_core_plugin_marketplace::npm_source;
pub(crate) use codex_core_plugin_marketplace::plugin_bundle_archive;
pub use codex_core_plugin_marketplace::store;

pub type LoadedPlugin = codex_plugin::LoadedPlugin<codex_config::McpServerConfig>;
pub type PluginLoadOutcome = codex_plugin::PluginLoadOutcome<codex_config::McpServerConfig>;

pub use app_mcp_routing::apps_route_available;
pub use command_migration::CommandDescriptionMode;
pub use command_migration::CommandMigrationProfile;
pub use command_migration::RewriteProfile as CommandRewriteProfile;
pub use command_migration::count_missing_commands_with_profile;
pub use command_migration::import_commands_with_profile;
pub use command_migration::missing_command_names_with_profile;
pub use discoverable::ToolSuggestDiscoverablePlugin;
pub use discoverable::ToolSuggestPluginDiscoveryInput;
pub use loader::PluginHookLoadOutcome;
pub use manager::ConfiguredMarketplace;
pub use manager::ConfiguredMarketplaceListOutcome;
pub use manager::ConfiguredMarketplacePlugin;
pub use manager::EffectivePluginsChange;
pub use manager::PluginDetail;
pub use manager::PluginDetailsUnavailableReason;
pub use manager::PluginInstallError;
pub use manager::PluginInstallOutcome;
pub use manager::PluginInstallRequest;
pub use manager::PluginListBackgroundTaskOptions;
pub use manager::PluginReadOutcome;
pub use manager::PluginReadRequest;
pub use manager::PluginUninstallError;
pub use manager::PluginsConfigInput;
pub use manager::PluginsManager;
pub use manager::RecommendedPluginCandidatesInput;
pub use marketplace_policy::allowed_configured_marketplace_names;
pub use marketplace_upgrade::ConfiguredMarketplaceUpgradeError as PluginMarketplaceUpgradeError;
pub use marketplace_upgrade::ConfiguredMarketplaceUpgradeOutcome as PluginMarketplaceUpgradeOutcome;
pub use provider::ExecutorPluginProvider;
pub use provider::ExecutorPluginProviderError;
pub use provider::ResolvedExecutorPlugin;
pub use remote::RecommendedPlugin;
pub use remote::RecommendedPluginsMode;
