[package]
name = "xedoc-tui-markdown"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "xedoc_tui_markdown"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
xedoc-tui-render = { workspace = true }
xedoc-utils-string = { workspace = true }
dirs = { workspace = true }
pulldown-cmark = { workspace = true }
ratatui = { workspace = true }
regex-lite = { workspace = true }
unicode-width = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
pretty_assertions = { workspace = true }
