use crate::city_lights::CityLightsStylize;
use std::time::Duration;
use std::time::Instant;

use ratatui::buffer::Buffer;
use ratatui::layout::Rect;
use ratatui::style::Style;
use ratatui::style::Styled;
use ratatui::style::Stylize;
use ratatui::text::Line;
use ratatui::text::Span;
use ratatui::widgets::Paragraph;
use ratatui::widgets::WidgetRef;

use crate::line_truncation::truncate_line_with_ellipsis_if_overflow;
use crate::render::line_utils::prefix_lines;
use crate::render::renderable::Renderable;
use crate::status::format_tokens_compact;
use crate::status_indicator_widget::fmt_elapsed_compact;
use crate::token_usage::TokenUsage;
use crate::tui::FrameRequester;

const MAX_VISIBLE_AGENTS: usize = 7;
const ELAPSED_REFRESH_INTERVAL: Duration = Duration::from_secs(1);
const DEFAULT_ACTIVITY: &str = "Working...";

#[derive(Clone, Debug)]
pub(crate) struct ActiveAgentEntry {
    pub(crate) name: String,
    pub(crate) started_at: Instant,
    pub(crate) provider_model: Option<String>,
    pub(crate) total_tokens: Option<i64>,
    pub(crate) token_usage: Option<TokenUsage>,
    /// Current activity summary generated by the sub-agent. Max 64 chars.
    pub(crate) current_activity: Option<String>,
}

pub(crate) struct ActiveAgentList {
    agents: Vec<ActiveAgentEntry>,
    frame_requester: FrameRequester,
}

impl ActiveAgentList {
    pub(crate) fn new(frame_requester: FrameRequester) -> Self {
        Self {
            agents: Vec::new(),
            frame_requester,
        }
    }

    pub(crate) fn set_agents(&mut self, agents: Vec<ActiveAgentEntry>) {
        self.agents = agents
            .into_iter()
            .filter_map(|mut entry| {
                entry.name = entry.name.trim().to_string();
                entry.provider_model = entry
                    .provider_model
                    .map(|provider_model| provider_model.trim().to_string())
                    .filter(|provider_model| !provider_model.is_empty());
                entry.total_tokens = entry.total_tokens.filter(|tokens| *tokens > 0);
                entry.token_usage = entry
                    .token_usage
                    .filter(|token_usage| !token_usage.is_zero());
                entry.current_activity = entry
                    .current_activity
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty());
                (!entry.name.is_empty()).then_some(entry)
            })
            .collect();
    }

    pub(crate) fn is_empty(&self) -> bool {
        self.agents.is_empty()
    }

    fn display_lines_at(&self, width: u16, now: Instant) -> Vec<Line<'static>> {
        if self.agents.is_empty() || width == 0 {
            return Vec::new();
        }

        let max_width = usize::from(width);
        let total = self.agents.len();
        let visible_agents = total.min(MAX_VISIBLE_AGENTS);
        let mut lines =
            Vec::with_capacity(1 + visible_agents + usize::from(total > visible_agents));
        let header_style = crate::city_lights::active_list_header_style();
        lines.push(vec!["• ".dim(), "Agents".set_style(header_style.bold())].into());

        let agent_lines = self.visible_agent_lines(now);
        lines.extend(prefix_lines(agent_lines, "  └ ".dim(), "    ".into()));

        lines
            .into_iter()
            .map(|line| truncate_line_with_ellipsis_if_overflow(line, max_width))
            .collect()
    }

    fn visible_agent_lines(&self, now: Instant) -> Vec<Line<'static>> {
        let mut lines: Vec<Line<'static>> = self
            .agents
            .iter()
            .take(MAX_VISIBLE_AGENTS)
            .map(|agent| Self::agent_line(agent, now))
            .collect();
        let hidden = self.agents.len().saturating_sub(MAX_VISIBLE_AGENTS);
        if hidden > 0 {
            lines.push(format!("... {hidden} more").dim().into());
        }
        lines
    }

    fn agent_line(agent: &ActiveAgentEntry, now: Instant) -> Line<'static> {
        let elapsed =
            fmt_elapsed_compact(now.saturating_duration_since(agent.started_at).as_secs());
        let mut spans = vec![
            "□ ".cl_cyan().bold(),
            Span::styled(agent.name.clone(), Style::default().cl_cyan().bold()),
        ];
        let activity = agent
            .current_activity
            .as_deref()
            .unwrap_or(DEFAULT_ACTIVITY);
        spans.push(Span::from(format!(" {activity}")));
        spans.push(Span::from(" (").dim());
        spans.push(Span::from(elapsed).dim());
        if let Some(provider_model) = agent.provider_model.as_ref() {
            spans.push(Span::from(", ").dim());
            spans.push(Span::from(provider_model.clone()).dim());
        }
        if let Some(token_usage) = agent.token_usage.as_ref() {
            spans.push(Span::from(", ").dim());
            spans.push(
                Span::from(format!(
                    "↓{}",
                    format_tokens_compact(token_usage.input_tokens).to_lowercase()
                ))
                .dim(),
            );
            spans.push(Span::from(", ").dim());
            spans.push(
                Span::from(format!(
                    "↑{}",
                    format_tokens_compact(token_usage.output_tokens).to_lowercase()
                ))
                .dim(),
            );
        } else if let Some(total_tokens) = agent.total_tokens {
            spans.push(Span::from(", ").dim());
            spans.push(Span::from(format_tokens_compact(total_tokens).to_lowercase()).dim());
        }
        spans.push(Span::from(")").dim());
        spans.into()
    }
}

impl Renderable for ActiveAgentList {
    fn render(&self, area: Rect, buf: &mut Buffer) {
        if area.is_empty() {
            return;
        }
        if !self.agents.is_empty() {
            self.frame_requester
                .schedule_frame_in(ELAPSED_REFRESH_INTERVAL);
        }
        Paragraph::new(self.display_lines_at(area.width, Instant::now())).render_ref(area, buf);
    }

    fn desired_height(&self, width: u16) -> u16 {
        self.display_lines_at(width, Instant::now()).len() as u16
    }
}

#[cfg(test)]
#[path = "active_agent_list_tests.rs"]
mod tests;
