[package]
edition.workspace = true
license.workspace = true
name = "xedoc-core-agent-registry"
version.workspace = true

[lib]
name = "xedoc_core_agent_registry"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
xedoc-otel = { workspace = true }
xedoc-protocol = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
