[package]
edition.workspace = true
license.workspace = true
name = "xedoc-core-mcp-runtime"
version.workspace = true

[lib]
name = "xedoc_core_mcp_runtime"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
xedoc-config = { workspace = true }
xedoc-core-approval-policy = { workspace = true }
xedoc-core-config = { workspace = true }
xedoc-core-plugins = { workspace = true }
xedoc-exec-server = { workspace = true }
xedoc-extension-api = { workspace = true }
xedoc-login = { workspace = true }
xedoc-mcp = { workspace = true }
xedoc-otel = { workspace = true }
xedoc-plugin = { workspace = true }
xedoc-protocol = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true, features = ["no-env-filter"] }
