// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider data required to replay a response item.
 */
export type ProviderItemMetadata = { "provider": "gemini",
/**
 * Opaque signature returned with the tool call.
 */
thought_signature: string, };
