//! Context fragments injected into model input.

#![deny(clippy::print_stdout, clippy::print_stderr)]

mod approved_command_prefix_saved;
mod available_plugins_instructions;
mod available_skills_instructions;
mod contextual_user_message;
mod current_time_reminder;
mod environment_context;
mod environments_instructions;
mod hook_additional_context;
mod inter_agent_completion_message;
mod internal_model_context;
mod legacy_apply_patch_exec_command_warning;
mod legacy_model_mismatch_warning;
mod legacy_unified_exec_process_limit_warning;
mod model_switch_instructions;
mod multi_agent_mode_instructions;
mod network_rule_saved;
mod permissions_instructions;
mod personality_spec_instructions;
mod plugin_instructions;
mod recommended_plugins_instructions;
mod rollout_budget;
mod subagent_notification;
mod token_budget_context;
mod turn_aborted;
mod user_instructions;
mod user_shell_command;
pub mod world_state;

pub use approved_command_prefix_saved::ApprovedCommandPrefixSaved;
pub use available_plugins_instructions::AvailablePluginsInstructions;
pub use available_skills_instructions::AvailableSkillsInstructions;
pub use codex_context_fragments::AdditionalContextDeveloperFragment;
pub use codex_context_fragments::AdditionalContextUserFragment;
pub use codex_context_fragments::ContextualUserFragment;
pub use codex_context_fragments::FragmentRegistration;
pub use codex_context_fragments::FragmentRegistrationProxy;
pub use codex_core_skills::SkillInstructions;
pub use contextual_user_message::is_contextual_user_fragment;
pub use contextual_user_message::parse_visible_hook_prompt_message;
pub use current_time_reminder::CurrentTimeReminder;
pub use environment_context::FileSystemContext;
pub use environment_context::NetworkContext;
pub use environments_instructions::EnvironmentsInstructions;
pub use hook_additional_context::HookAdditionalContext;
pub use inter_agent_completion_message::InterAgentCompletionMessage;
pub use internal_model_context::InternalContextSource;
pub use internal_model_context::InternalModelContextFragment;
pub use internal_model_context::InvalidInternalContextSource;
pub use legacy_apply_patch_exec_command_warning::LegacyApplyPatchExecCommandWarning;
pub use legacy_model_mismatch_warning::LegacyModelMismatchWarning;
pub use legacy_unified_exec_process_limit_warning::LegacyUnifiedExecProcessLimitWarning;
pub use model_switch_instructions::ModelSwitchInstructions;
pub use multi_agent_mode_instructions::MultiAgentModeInstructions;
pub use network_rule_saved::NetworkRuleSaved;
pub use permissions_instructions::ApprovalPromptContext;
pub use permissions_instructions::PermissionsInstructions;
pub use personality_spec_instructions::PersonalitySpecInstructions;
pub use plugin_instructions::PluginInstructions;
pub use recommended_plugins_instructions::RecommendedPluginsInstructions;
pub use rollout_budget::RolloutBudgetContext;
pub use subagent_notification::SubagentNotification;
pub use token_budget_context::AutoCompactFallbackPrompt;
pub use token_budget_context::ContextWindowGuidance;
pub use token_budget_context::TokenBudgetContext;
pub use token_budget_context::TokenBudgetRemainingContext;
pub use token_budget_context::TokenBudgetReminder;
pub use turn_aborted::TurnAborted;
pub use user_instructions::UserInstructions;
pub use user_shell_command::UserShellCommand;
