[package]
edition.workspace = true
license.workspace = true
name = "xedoc-provider-e2e"
version.workspace = true
autotests = false

[[test]]
name = "proxy_reference_happy_paths"
path = "tests/proxy_reference_happy_paths.rs"

[lints]
workspace = true

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
toml = { workspace = true }
xedoc-exec = { workspace = true }
xedoc-http-client = { workspace = true }
xedoc-login = { workspace = true }
xedoc-model-provider = { workspace = true }
xedoc-model-provider-info = { workspace = true }
xedoc-models-manager = { workspace = true }
xedoc-protocol = { workspace = true }
xedoc-utils-cargo-bin = { workspace = true }
xedoc-utils-absolute-path = { workspace = true }
