// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transient status update for a compaction run.
 */
export type CompactionProgressNotification = {
/**
 * Thread whose compaction run produced this update.
 */
threadId: string,
/**
 * Current compaction lifecycle stage.
 */
stage: string, };
