// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the client concluded an extension interaction.
 */
export type ExtensionInteractionOutcome = "accepted" | "cancelled" | "dismissed";
