// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Presentation severity for an extension interaction notice.
 */
export type ExtensionInteractionNoticeLevel = "info" | "success" | "warning" | "error";
