// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selected model route in an extension interaction.
 */
export type ExtensionInteractionRoute = { providerId: string, model: string, reasoningEffort: string, };
