// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Script-controlled filtering for a select field.
 */
export type ExtensionInteractionSelectSearch = { placeholder: string | null, };
