// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ExtensionInteractionOutcome } from "./ExtensionInteractionOutcome";
import type { ExtensionInteractionSelectedAction } from "./ExtensionInteractionSelectedAction";

/**
 * A response to a generic scripted extension interaction.
 */
export type ExtensionInteractionRequestResponse = { extensionId: string, interactionId: string, continuation: string, stateRevision: string | null, outcome: ExtensionInteractionOutcome, action: ExtensionInteractionSelectedAction | null, values: JsonValue, };
