// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One script-owned confirmation row.
 */
export type ExtensionInteractionRow = { text: string, indent: number, };
