// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque selectable option in an extension interaction form.
 */
export type ExtensionInteractionOption = { id: string, label: string, description: string | null, disabled: boolean | null, };
