// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionInteractionEligibleRoute } from "./ExtensionInteractionEligibleRoute";
import type { ExtensionInteractionOption } from "./ExtensionInteractionOption";
import type { ExtensionInteractionRoute } from "./ExtensionInteractionRoute";

/**
 * A field in an extension interaction form.
 */
export type ExtensionInteractionField = { "type": "select", id: string, label: string, description: string | null, value: string | null, current: string | null, options: Array<ExtensionInteractionOption>, } | { "type": "boolean", id: string, label: string, description: string | null, value: boolean, } | { "type": "text", id: string, label: string, description: string | null, value: string, maxBytes: number, sensitive: boolean, } | { "type": "modelRoute", id: string, label: string, description: string | null, value: ExtensionInteractionRoute | null, eligibleRoutes: Array<ExtensionInteractionEligibleRoute>, };
