// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model route eligible for selection in an extension interaction.
 */
export type ExtensionInteractionEligibleRoute = { providerId: string, model: string, reasoningEfforts: Array<string>, };
