// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionInteractionRow } from "./ExtensionInteractionRow";

/**
 * A titled group of script-owned confirmation rows.
 */
export type ExtensionInteractionSection = { title: string | null, rows: Array<ExtensionInteractionRow>, };
