// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque action selected by the client.
 */
export type ExtensionInteractionSelectedAction = { id: string, };
