// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionInteractionSurface } from "./ExtensionInteractionSurface";

/**
 * A generic constrained interaction requested by an extension script.
 */
export type ExtensionInteractionRequestParams = { threadId: string, turnId: string, requestId: string, extensionId: string, interactionId: string, continuation: string, stateRevision: string | null, expiresAt: bigint, surface: ExtensionInteractionSurface, };
