// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ModelRouterSettingsHostAction } from "./ModelRouterSettingsHostAction";

/**
 * An opaque action supplied by an extension interaction.
 */
export type ExtensionInteractionAction = { id: string, opens: string | null, hostAction: ModelRouterSettingsHostAction | null, label: string | null, keyBindings: Array<string>, value: JsonValue | null, };
