// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionInteractionAction } from "./ExtensionInteractionAction";
import type { ExtensionInteractionField } from "./ExtensionInteractionField";

/**
 * A form in an extension interaction surface.
 */
export type ExtensionInteractionForm = { id: string, title: string, subtitle: string | null, fields: Array<ExtensionInteractionField>, submit: ExtensionInteractionAction, cancel: ExtensionInteractionAction | null, };
