// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A visible label/value pair in an extension interaction confirmation.
 */
export type ExtensionInteractionDetail = { label: string, value: string, };
