// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionInteractionAction } from "./ExtensionInteractionAction";

/**
 * A selectable row in an extension interaction menu.
 */
export type ExtensionInteractionMenuItem = { id: string, label: string, description: string | null, action: ExtensionInteractionAction, current: boolean | null, disabled: boolean | null, };
