// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ManagedModelSettings } from "./ManagedModelSettings";

export type ManagedProviderSettings = { id: string, displayName: string, defaultModel: string, fastModel: string, defaultReasoningEffort: ReasoningEffort, apiKeyConfigured: boolean, oauthSupported: boolean, oauthConfigured: boolean, models: Array<ManagedModelSettings>, };
