// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata-only view of one recent local model-router decision.
 */
export type ModelRouterReportDecision = { decisionId: string, scope: string, classId: string | null, score: number | null, margin: number | null, disposition: string, reason: string, fallback: boolean, policyRevision: string, proposedProviderId: string | null, proposedModelSlug: string | null, proposedReasoningEffort: string | null, effectiveProviderId: string | null, effectiveModelSlug: string | null, effectiveReasoningEffort: string | null,
/**
 * Creation time as whole Unix seconds.
 */
createdAt: number, };
