// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Starts a local browser report for model-router activity.
 */
export type ModelRouterReportOpenParams = Record<string, never>;
