// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionInteractionRequestResponse } from "./ExtensionInteractionRequestResponse";

export type ModelRouterSettingsRespondParams = { threadId?: string | null, response: ExtensionInteractionRequestResponse, };
