// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

export type ModelManagerUpdateParams = { "type": "providerDefaults", provider_id: string, default_model: string, fast_model: string, default_reasoning_effort: ReasoningEffort, } | { "type": "modelSettings", provider_id: string, model_id: string, context_window: bigint, max_context_window: bigint, auto_compact_token_limit: bigint, base_instructions: string, };
