// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterActivityState } from "./ModelRouterActivityState";
import type { ModelRouterScope } from "./ModelRouterScope";

/**
 * Transient local model-router classification lifecycle update.
 */
export type ModelRouterActivityNotification = { threadId: string, turnId: string, scope: ModelRouterScope, state: ModelRouterActivityState, };
