// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rating and allowed model range for one approval classification choice.
 */
export type ModelRouterApprovalClassRating = { points: number, minimumModelClass: string, maximumModelClass: string, };
