// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterPolicyClass } from "./ModelRouterPolicyClass";

/**
 * Replace the user-editable routing policy controls while preserving classifier weights.
 */
export type ModelRouterPolicyWriteParams = { minimumScore: number, minimumMargin: number, classes: Array<ModelRouterPolicyClass>, };
