// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterAbControlAction } from "./ModelRouterAbControlAction";

/**
 * Request a root-thread model-router A/B control action.
 */
export type ModelRouterAbControlParams = { threadId: string, action: ModelRouterAbControlAction, };
