// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterRankedRoute } from "./ModelRouterRankedRoute";

/**
 * The score domain and ordered automatic-routing candidates.
 */
export type ModelRouterRanking = { minimumScore: number, maximumScore: number, ladder: Array<ModelRouterRankedRoute>, };
