// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterSettingsInteraction } from "./ModelRouterSettingsInteraction";

export type ModelRouterSettingsRespondResponse = { interaction: ModelRouterSettingsInteraction | null, error: string | null, };
