// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounded input for reading the local model-router report.
 */
export type ModelRouterReportReadParams = {
/**
 * Inclusive UTC-day start, as whole Unix seconds.
 */
fromDay?: number,
/**
 * Inclusive UTC-day end, as whole Unix seconds.
 */
throughDay?: number,
/**
 * Maximum recent decisions to return, capped by the server.
 */
recentLimit?: number | null, };
