// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterPolicyClass } from "./ModelRouterPolicyClass";

/**
 * The stable, user-editable portion of the standalone model-router policy.
 */
export type ModelRouterPolicy = { policyRevision: string, classifierRevision: string, minimumScore: number, minimumMargin: number, classes: Array<ModelRouterPolicyClass>, };
