// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterEffectiveRoute } from "./ModelRouterEffectiveRoute";
import type { ModelRouterRoute } from "./ModelRouterRoute";
import type { ModelRouterScope } from "./ModelRouterScope";

/**
 * A dedicated, structured request to approve a proposed model route.
 */
export type ModelRouterApprovalParams = { approvalId: string, threadId: string, turnId: string, scope: ModelRouterScope, predictedClassification: string, proposedRoute: ModelRouterRoute, currentRoute: ModelRouterEffectiveRoute, score: number, margin: number, classifierRevision: string, policyRevision: string, promptSha256: string, };
