// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The action a user takes on a model-router proposal.
 */
export type ModelRouterApprovalAction = "approve" | "reject" | "override";
