// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit host capabilities available to model-router settings scripts.
 */
export type ModelRouterSettingsHostAction = "open-report" | "arm-ab" | "disable-ab";
