// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterReportDay } from "./ModelRouterReportDay";
import type { ModelRouterReportDecision } from "./ModelRouterReportDecision";

/**
 * Bounded report assembled from local model-router state.
 */
export type ModelRouterReportReadResponse = {
/**
 * Inclusive UTC-day start used for `days`.
 */
fromDay: number,
/**
 * Inclusive UTC-day end used for `days`.
 */
throughDay: number, days: Array<ModelRouterReportDay>,
/**
 * Whether aggregate rows exceeded the report's fixed response limit.
 */
daysTruncated: boolean, recentDecisions: Array<ModelRouterReportDecision>, };
