// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A short-lived local URL for the model-router browser report.
 */
export type ModelRouterReportOpenResponse = {
/**
 * Loopback URL whose fragment contains the read-only capability.
 */
url: string, };
