// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A provider/model route with user-assigned capability tags.
 */
export type ModelRouterCapability = { provider: string, model: string, tags: Array<string>, };
