// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * A user-editable position in the automatic-routing model ladder.
 */
export type ModelRouterRankedRoute = { rank: number, class: string, provider: string, model: string, reasoningEffort: ReasoningEffort, };
