// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionInteractionSurface } from "./ExtensionInteractionSurface";

export type ModelRouterSettingsInteraction = { interactionId: string, continuation: string, stateRevision: string, surface: ExtensionInteractionSurface, };
