// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterApprovalAction } from "./ModelRouterApprovalAction";

/**
 * The response to a model-router approval request.
 */
export type ModelRouterApprovalResponse = { action: ModelRouterApprovalAction, classification: string | null, classifications: { [key in string]?: string }, };
