// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selectable model route proposed by the model router.
 */
export type ModelRouterRoute = { providerId: string, modelSlug: string, reasoningEffort: string, };
