// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * A user-editable routing class in the standalone model-router policy.
 */
export type ModelRouterPolicyClass = { id: string, minimumReasoningEffort: ReasoningEffort, requiredCapabilities: Array<string>, };
