// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A direct user control for the next root-turn A/B experiment.
 */
export type ModelRouterAbControlAction = "armNext" | "disable";
