// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterDecisionReason } from "./ModelRouterDecisionReason";
import type { ModelRouterDisposition } from "./ModelRouterDisposition";
import type { ModelRouterEffectiveRoute } from "./ModelRouterEffectiveRoute";
import type { ModelRouterScope } from "./ModelRouterScope";

/**
 * Experimental metadata-only record of one local model-router decision.
 *
 * This notification never contains prompt or output text.
 */
export type ModelRouterDecisionNotification = { decisionId: string, threadId: string, turnId: string, scope: ModelRouterScope, disposition: ModelRouterDisposition, reason: ModelRouterDecisionReason, policyRevision: string, proposedProviderId: string, proposedModelSlug: string, proposedReasoningEffort: string, effectiveRoute: ModelRouterEffectiveRoute, promptSha256: string, promptOriginalBytes: number, promptTruncated: boolean,
/**
 * Unix timestamp in whole seconds when this immutable decision was made.
 */
createdAt: number, };
