// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouterRoute } from "./ModelRouterRoute";

/**
 * One available policy-ranked route for approval preview calculation.
 */
export type ModelRouterApprovalRankedRoute = { rank: number, modelClass: string, route: ModelRouterRoute, };
