// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One persisted UTC-day aggregate for the local model router.
 */
export type ModelRouterReportDay = {
/**
 * UTC midnight as whole Unix seconds.
 */
day: number, providerId: string, modelSlug: string, scope: string, reasoningEffort: string | null, decisions: number, invocations: number, inputTokens: number | null, cachedInputTokens: number | null, outputTokens: number | null, totalCostUsd: number | null, normalizedBaselineUsd: number | null, estimatedSavingsUsd: number | null, abExperimentOverheadUsd: number | null, attributedInvocations: number, unattributedInvocations: number, missingUsageInvocations: number, unknownPriceInvocations: number, classifiedDecisions: number, fallbackDecisions: number, averageScore: number | null, averageMargin: number | null, };
