// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginInterface = { displayName: string | null, shortDescription: string | null, longDescription: string | null, developerName: string | null, category: string | null, capabilities: Array<string>, websiteUrl: string | null, privacyPolicyUrl: string | null, termsOfServiceUrl: string | null,
/**
 * Starter prompts for the plugin. Capped at 3 entries with a maximum of
 * 128 characters per entry.
 */
defaultPrompt: Array<string> | null, brandColor: string | null,
/**
 * Local composer icon path, resolved from the installed plugin package.
 */
composerIcon: AbsolutePathBuf | null,
/**
 * Local logo path, resolved from the installed plugin package.
 */
logo: AbsolutePathBuf | null,
/**
 * Local dark-mode logo path, resolved from the installed plugin package.
 */
logoDark: AbsolutePathBuf | null,
/**
 * Local screenshot paths, resolved from the installed plugin package.
 */
screenshots: Array<AbsolutePathBuf>, };
