// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionSummary } from "./RemoteSessionSummary";

/**
 * Result of cancelling a remote session turn.
 */
export type RemoteSessionCancelResponse = { remoteSession: RemoteSessionSummary, };
