// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionHostRole } from "./RemoteSessionHostRole";
import type { RemoteSessionStatus } from "./RemoteSessionStatus";

/**
 * Updates a remote session from the host-managed remote-agent extension.
 */
export type RemoteSessionUpdateParams = { registrationId: string, remoteSessionId: string, status: RemoteSessionStatus, activitySummary?: string | null, outputDelta?: string | null, outputCursor?: string | null, remoteTurnId?: string | null, workspaceId?: string | null, hostName?: string | null, hostRole?: RemoteSessionHostRole | null, };
