// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state reported for a remote session.
 */
export type RemoteSessionStatus = "idle" | "running" | "completed" | "failed" | "cancelled" | "expired" | "detached";
