// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lists locally registered remote sessions for one root thread.
 */
export type RemoteSessionListParams = { threadId: string, };
