// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionSummary } from "./RemoteSessionSummary";

/**
 * Returns the opaque local session ID for a registered remote identity.
 */
export type RemoteSessionRegisterResponse = { remoteSession: RemoteSessionSummary, };
