// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attaches the caller's root thread to a registered remote session.
 */
export type RemoteSessionAttachParams = { threadId: string, remoteSessionId: string, };
