// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionHostRole } from "./RemoteSessionHostRole";
import type { RemoteSessionStatus } from "./RemoteSessionStatus";

/**
 * Root-thread scoped projection of a remote session.
 */
export type RemoteSessionSummary = { remoteSessionId: string, hostId: string, remoteThreadId: string, workspaceId: string | null, hostName: string | null, hostRole: RemoteSessionHostRole | null, status: RemoteSessionStatus, activeTurnId: string | null, activitySummary: string | null, outputCursor: string | null, };
