// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detaches the caller's root thread from a registered remote session.
 */
export type RemoteSessionDetachParams = { threadId: string, remoteSessionId: string, };
