// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sends input or steering to a registered remote session.
 */
export type RemoteSessionInputParams = { threadId: string, remoteSessionId: string, message: string, expectedTurnId?: string | null, };
