// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Broker result returned by the remote-agent extension.
 */
export type RemoteSessionControlResponse = { success: boolean, result: JsonValue, };
