// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fixed broker actions permitted through the remote-agent extension.
 */
export type RemoteSessionControlAction = "attach" | "read" | "send" | "steer" | "cancel" | "detach";
