// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionSummary } from "./RemoteSessionSummary";

/**
 * Signals a change to a root-thread-scoped remote session projection.
 */
export type RemoteSessionUpdatedNotification = { threadId: string, remoteSession: RemoteSessionSummary, outputDelta: string | null, };
