// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reads one locally registered remote session.
 */
export type RemoteSessionReadParams = { threadId: string, remoteSessionId: string, cursor?: string | null, limit?: number | null, };
