// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionSummary } from "./RemoteSessionSummary";

/**
 * Bounded output and summary for a remote session.
 */
export type RemoteSessionReadResponse = { remoteSession: RemoteSessionSummary, output: string, };
