// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionSummary } from "./RemoteSessionSummary";

/**
 * Registered remote sessions belonging to one root thread.
 */
export type RemoteSessionListResponse = { remoteSessions: Array<RemoteSessionSummary>, };
