// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";

/**
 * One transcript item of a remote session, in the remote host's own thread-item shape so a
 * client renders it like an item of a local thread.
 */
export type RemoteSessionItem = { turnId: string, item: ThreadItem, };
