// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionControlAction } from "./RemoteSessionControlAction";

/**
 * Requests one broker operation from the remote-agent extension.
 */
export type RemoteSessionControlParams = { action: RemoteSessionControlAction, hostId: string, threadId: string, message: string | null, expectedTurnId: string | null, cursor: string | null, limit: number | null, };
