// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty successful response for a remote-session update.
 */
export type RemoteSessionUpdateResponse = Record<string, never>;
