// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteSessionItem } from "./RemoteSessionItem";
import type { RemoteSessionSummary } from "./RemoteSessionSummary";

/**
 * Bounded output and summary for a remote session.
 */
export type RemoteSessionReadResponse = { remoteSession: RemoteSessionSummary,
/**
 * Text projection of the page, for clients that do not render items.
 */
output: string,
/**
 * Structured transcript items of the page.
 */
items: Array<RemoteSessionItem>, };
