// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable session fields a script may cache until the next replacement update.
 */
export type SessionScriptSession = { sessionId: string, threadId: string, title: string | null, projectName: string | null, projectRoot: string | null, cwd: string, };
