// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Invokes one approved session-extension slash command.
 */
export type SessionExtensionCommandInvokeParams = { threadId: string, extensionId: string, command: string, arguments: Array<string>, };
