// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionExtensionCommand } from "./SessionExtensionCommand";

/**
 * Announces the replacement command set after approval, activation, or disabling.
 */
export type SessionExtensionCommandsUpdatedNotification = { threadId: string, commands: Array<SessionExtensionCommand>, };
