// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionScriptPrompt } from "./SessionScriptPrompt";
import type { SessionScriptSession } from "./SessionScriptSession";
import type { SessionScriptThread } from "./SessionScriptThread";
import type { Turn } from "./Turn";

/**
 * Current, bounded state for a single session-script registration.
 */
export type SessionScriptSnapshot = { revision: number, session: SessionScriptSession, thread: SessionScriptThread, turn: Turn | null, pendingPrompts: Array<SessionScriptPrompt>, };
