// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledges that an approved session-extension command was dispatched.
 */
export type SessionExtensionCommandInvokeResponse = Record<string, never>;
