// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionScriptPromptKind } from "./SessionScriptPromptKind";
import type { SessionScriptPromptRequest } from "./SessionScriptPromptRequest";

export type SessionScriptPromptOpenedNotification = { registrationId: string, promptId: string, kind: SessionScriptPromptKind, threadId: string, turnId: string | null, itemId: string | null, canRespond: boolean, responseLease: string | null, request: SessionScriptPromptRequest, };
