// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionExtensionMessageLevel } from "./SessionExtensionMessageLevel";

/**
 * Posts a user-visible message from a registered session script.
 */
export type SessionScriptMessageParams = { registrationId: string, level: SessionExtensionMessageLevel, message: string, };
