// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Preserves the existing v2 request shape without making it actionable for observers.
 */
export type SessionScriptPromptRequest = { method: string, params: JsonValue, };
