// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionExtensionCommand } from "./SessionExtensionCommand";

/**
 * Approved slash commands for one loaded root thread.
 */
export type SessionExtensionListResponse = { commands: Array<SessionExtensionCommand>, };
