// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionScriptPromptResponse } from "./SessionScriptPromptResponse";

export type SessionScriptRespondParams = { registrationId: string, promptId: string, responseLease: string, response: SessionScriptPromptResponse, };
