// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionScriptPromptKind } from "./SessionScriptPromptKind";

/**
 * Selects the bounded stream of events delivered to a session script.
 */
export type SessionScriptSubscriptionsParams = { modelResponseDeltas?: boolean, modelResponseCompleted?: boolean, userMessages?: boolean, turnCompleted?: boolean, prompts?: Array<SessionScriptPromptKind> | null, sessionUpdates?: boolean, };
