// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A prompt class that a session script may observe.
 */
export type SessionScriptPromptKind = "requestUserInput" | "extensionInteraction" | "commandExecutionApproval" | "fileChangeApproval" | "permissionsApproval" | "mcpElicitation";
