// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionScriptCapability } from "./SessionScriptCapability";
import type { SessionScriptSnapshot } from "./SessionScriptSnapshot";

export type SessionScriptRegisterResponse = { registrationId: string, grantedCapabilities: Array<SessionScriptCapability>, snapshot: SessionScriptSnapshot, };
