// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionScriptCapability } from "./SessionScriptCapability";
import type { SessionScriptIdentityParams } from "./SessionScriptIdentityParams";
import type { SessionScriptSubscriptionsParams } from "./SessionScriptSubscriptionsParams";

/**
 * Registers the initialized connection as a restricted session script.
 */
export type SessionScriptRegisterParams = { threadId: string, script: SessionScriptIdentityParams, subscriptions: SessionScriptSubscriptionsParams, requestedCapabilities?: Array<SessionScriptCapability> | null, };
