// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reads the approved session-extension commands for one loaded root thread.
 */
export type SessionExtensionListParams = { threadId: string, };
