// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionScriptPromptKind } from "./SessionScriptPromptKind";
import type { SessionScriptPromptRequest } from "./SessionScriptPromptRequest";

/**
 * A bounded projection of a prompt that is open for this script's thread.
 */
export type SessionScriptPrompt = { promptId: string, kind: SessionScriptPromptKind, threadId: string, turnId: string | null, itemId: string | null, canRespond: boolean, responseLease: string | null, request: SessionScriptPromptRequest, };
