// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageOptimizerInsights } from "./TokenUsageOptimizerInsights";
import type { TokenUsageOptimizerLevel } from "./TokenUsageOptimizerLevel";

export type TokenUsageOptimizerReadResponse = { enabled: boolean, level: TokenUsageOptimizerLevel, reductionCount: bigint, tokensSaved: bigint, insights: TokenUsageOptimizerInsights, };
