// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsageOptimizerBreakdown = { dimension: string, reductions: bigint, bytesIn: bigint, bytesOut: bigint, retrievals: bigint, reruns: bigint, costSavedUsd: number | null, };
