// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageOptimizerReportDay } from "./TokenUsageOptimizerReportDay";

export type TokenUsageOptimizerReportResponse = { sinceDay: bigint, untilDay: bigint, days: Array<TokenUsageOptimizerReportDay>, reductions: bigint, tokensSaved: bigint, costSavedUsd: number, };
