// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageOptimizerBreakdown } from "./TokenUsageOptimizerBreakdown";
import type { TokenUsageOptimizerTopReduction } from "./TokenUsageOptimizerTopReduction";

export type TokenUsageOptimizerInsights = { byKind: Array<TokenUsageOptimizerBreakdown>, byReducer: Array<TokenUsageOptimizerBreakdown>, byTool: Array<TokenUsageOptimizerBreakdown>, topReductions: Array<TokenUsageOptimizerTopReduction>, retrievals: bigint, spilled: bigint, };
