// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageOptimizerLevel } from "./TokenUsageOptimizerLevel";

export type TokenUsageOptimizerWriteParams = { enabled?: boolean | null, level?: TokenUsageOptimizerLevel | null, expectedVersion?: string | null, resetStats?: boolean, };
