// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XedocErrorInfo } from "./XedocErrorInfo";

export type TurnError = { message: string, xedocErrorInfo: XedocErrorInfo | null, additionalDetails: string | null, };
