[package]
edition.workspace = true
license.workspace = true
name = "xedoc-core-client"
version.workspace = true

[lib]
name = "xedoc_core_client"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
xedoc-api = { workspace = true }
xedoc-http-client = { workspace = true }
xedoc-login = { workspace = true }
xedoc-model-provider = { workspace = true }
xedoc-model-provider-info = { workspace = true }
xedoc-otel = { workspace = true }
xedoc-provider-anthropic = { workspace = true }
xedoc-protocol = { workspace = true }
xedoc-response-debug-context = { workspace = true }
xedoc-tools = { workspace = true }
xedoc-utils-output-truncation = { workspace = true }
xedoc-utils-string = { workspace = true }
eventsource-stream = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
wiremock = { workspace = true }
